#!/usr/bin/env bash

#------------------------------------------------------------------------------------
set -e  # Fail on first error

# Some useful global variables and constants
CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
SCRIPT_NAME="$0"

source $CURRENT_DIR/../.conf
source $CURRENT_DIR/../log4bash.sh
source $CURRENT_DIR/../util.sh
#-----------------------------------------------------------------------------------

DATASET_NAME="$1"
REPR_NAME="$2"

checkVarInConf PARSED_DATASETS_DIR
checkVarInConf PATH_TO_PYTHON_PROJECT

path_to_dataset=${PARSED_DATASETS_DIR}/${DATASET_NAME}/repr/${REPR_NAME}

cd ${PATH_TO_PYTHON_PROJECT}
conda activate fastai

CMD="python logrec/dataprep/vocabsize.py --base-from ${PARSED_DATASETS_DIR} ${path_to_dataset}"
echo "Running the following command:"
printGreen "${CMD}"
${CMD}