#!/usr/bin/env bash

#------------------------------------------------------------------------------------
set -e  # Fail on first error

# Some useful global variables and constants
CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
SCRIPT_NAME="$0"

source $CURRENT_DIR/../.conf
source $CURRENT_DIR/../log4bash.sh
source $CURRENT_DIR/../util.sh
#-----------------------------------------------------------------------------------

DATASET_NAME="$1"
REPR_NAME="$2"

checkVarInConf PARSED_DATASETS_DIR
checkVarInConf PATH_TO_PROJECT
checkVarInConf PYTHON

cd ${PATH_TO_PROJECT}

CMD="${PYTHON} logrec/dataprep/vocabsize.py --base-from ${PARSED_DATASETS_DIR} ${DATASET_NAME} ${REPR_NAME}"
echo "Running the following command:"
printGreen "${CMD}"
${CMD}
cd -
